version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Pre-build phase...
      - echo Nothing to do here

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - python -m unittest discover || echo "No tests found"

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'

